name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
      - name: copy out pdf
        uses: actions/upload-artifact@v2
        with:
          # the filename in workflow tab
          name: resume
          # resume.tex generates resume.pdf
          # copy this file to workflow tab
          path: resume.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        # only release with git-tag
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
